name: Deploy to Preview Channel

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          touch .env.production
          echo ${{ secrets.PRODUCTION_ENV }} >> .env.production
          cat .env.production
      - run: yarn && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE }}"
          expires: 30d
          projectId: helloworld-90243
