name: Release

on:
  push:
    branches:
      - main

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Must touch after checkout or the file will not available
      - run: |
          touch .env
          echo ${{ secrets.PRODUCTION_ENV }} >> .env
          cat .env 
      - run: yarn && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE }}"
          projectId: helloworld-90243
          channelId: live